server.port=8082
spring.application.name=order-service
spring.datasource.url=jdbc:mysql://localhost:3306/order_db
spring.datasource.username=root
spring.datasource.password=Root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ---- CIRCUIT BREAKER ----
#resilience4j.circuitbreaker.instances.paymentService.failure-rate-threshold=50
#resilience4j.circuitbreaker.instances.paymentService.minimum-number-of-calls=5
#resilience4j.circuitbreaker.instances.paymentService.wait-duration-in-open-state=10s

resilience4j.circuitbreaker.instances.productService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.productService.minimum-number-of-calls=5

resilience4j.circuitbreaker.instances.notificationService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.notificationService.minimum-number-of-calls=5

resilience4j.circuitbreaker.instances.paymentCB.slidingWindowSize=5
resilience4j.circuitbreaker.instances.paymentCB.failureRateThreshold=80
resilience4j.circuitbreaker.instances.paymentCB.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.paymentCB.permittedNumberOfCallsInHalfOpenState=2

resilience4j.retry.instances.paymentRetry.maxAttempts=3
resilience4j.retry.instances.paymentRetry.waitDuration=500ms
resilience4j.retry.instances.paymentRetry.enableExponentialBackoff=true
resilience4j.retry.instances.paymentRetry.exponentialBackoffMultiplier=2

resilience4j.timelimiter.instances.paymentCB.timeoutDuration=1s

# -------- RATE LIMITER CONFIG --------
resilience4j.ratelimiter.instances.paymentRateLimiter.limitForPeriod=3
resilience4j.ratelimiter.instances.paymentRateLimiter.limitRefreshPeriod=10s
resilience4j.ratelimiter.instances.paymentRateLimiter.timeoutDuration=0


logging.level.io.github.resilience4j.retry=DEBUG


# Kafka broker
spring.kafka.bootstrap-servers=localhost:9092

# Producer configs
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# (Optional but recommended)
spring.kafka.template.default-topic=order-events



test.failure.enabled=false

#logging.file.name=application.log
#logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
